### ISSUE TITLE
Directed Graph Propose?

### ISSUE THREAD

**Issue by chenhongyu2048** [raywan-110/AdaQP#2]
First of all it is a very good job.
But when I reproduced it I found that it seems to have some problems with the ogbn-arxiv dataset. Reddits and ogbn-products are both undirected graphs (I didn't download the other two datasets), i.e. is_bidirected= False. 
So the framework does not seem to work properly with is_bidirected=true.

**Comment by MrChen-NJU** [comment]
I'll probably give a more detailed description of the bug I've encountered tomorrow.

**Comment by MrChen-NJU** [comment]
The question could be more detailed:
When processing an unbidirected graph, the `reverse` will build a totally different message-passing graph in the backward phase, so the central graph and marginal graph are both different and needed to be rebuild.
This is why when is_bidirected = False and use_parallel = True, the program will break down.
I hope I have described the issue clearly.

**Comment by MrChen-NJU** [comment]
This question may be a little difficult to solve, because it will need a rebuild of the backward propagation phase, such as the buffer, bwd_graph, send_idx and recv_idx.
An easy solution is to transfer all the datasets to be bidirected.
I'm also looking foward to a better solution.

**Comment by raywan-110** [comment]
thanks for your comment! Currently, we handle undirected graphs in most cases, but we also provide the partition method for directed graphs in our code. Will check this issue and notify you as soon as we fix it. Thanks!
